### ISSUE TITLE
get_current_request returns None when internal error happens

### ISSUE THREAD

**Issue by r26zhao** [ninemoreminutes/django-crum#4]
Hello, I'm trying to capture the current request when it return 500. However it returns None.

**Comment by cchurch** [comment]
Are you trying to capture the request within a [`handler500`](https://docs.djangoproject.com/en/2.1/ref/urls/#handler500) function?

**Comment by cchurch** [comment]
Hmm... I don't have a test for that... let me see what I can do.

**Comment by cchurch** [comment]
So... the request is passed as the first argument to the [500 (server error) view](https://docs.djangoproject.com/en/2.1/ref/views/#the-500-server-error-view). Is there a particular reason you need to retrieve it via `get_current_request` instead?

If you have code that needs to run as part of the error handler and it's not straightforward to pass the request directly, you could do something like:

```python
from crum import set_current_request

def handle_500(request):
    try:
        set_current_request(request)
        # do your stuff / return a custom error page
    finally:
        set_current_request(None)
```

**Comment by r26zhao** [comment]
Thank you very much. Solved my problem. Thanks bro.

**Comment by r26zhao** [comment]
Thank you very much. Solved my problem. Thanks bro.
