### ISSUE TITLE
How to get user id?

### ISSUE THREAD

**Issue by ktaranov** [ninemoreminutes/django-crum#8]
Great thanks for this package. Could you help with returning user id instead user name?

**Comment by cchurch** [comment]
`get_current_user()` should return the `User` instance, so `user.id` (or `user.pk`) should give you the current user ID. When no user is logged in, you'll get the `AnonymousUser` object, whose id is `None`.

**Comment by ktaranov** [comment]
Awesome, it works.

**Comment by ktaranov** [comment]
Sorry, for reopened issue, but after deploy project to Cnetos 7 with gunicorn get issue with get_current_user (on development environment Win10 + runtestserver all works).

My models:
```python
class AuditoryType(models.Model):
    id = models.AutoField(db_column='id', primary_key=True, blank=True, null=False)
    name = models.TextField(db_column='name', max_length=500, unique=True, null=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    auth_user_id = models.ForeignKey('auth.User', db_column='auth_user_id', null=False, blank=False,
                                     default=None, on_delete=models.PROTECT)

    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.auth_user_id = user
        self.auth_user_id = user
        super(AuditoryType, self).save(*args, **kwargs)

    class Meta:
        managed = False
        db_table = 'auditory_type'

    def __str__(self):
        return self.name
```
Error:
`null value in column "auth_user_id" violates not-null constraint
DETAIL:  Failing row contains (10, ttt, 2020-02-08 08:10:31.635609+00, 2020-02-08 08:10:31.635657+00, null).`

**Comment by dezoito** [comment]
@ktaranov,

I'm experiencing the same issue (using Django 3.2), Linix Mint and running in development mode.

Django-crum is correctly set up in settings, but both `get_current_user()` and `get_current_request()` return `None`, even the the user is authenticated.

Were you able to find a solution?

**Comment by ktaranov** [comment]
Could you post code example in issues and mention me again? I don’t remember how we fix it but today its work properly>

From: Dezoito ***@***.***>
Reply to: ninemoreminutes/django-crum ***@***.***>
Date: Tuesday, 13 April 2021, 21:22
To: ninemoreminutes/django-crum ***@***.***>
Cc: Константин Таранов ***@***.***>, Mention ***@***.***>
Subject: Re: [ninemoreminutes/django-crum] How to get user id? (#8)


@ktaranov<https://github.com/ktaranov>,

I'm experiencing the same issue (using Django 3.2), Linix Mint and running in development mode.

Django-crum is correctly set up in settings, but both get_current_user() and get_current_request() return None, even the the user is authenticated.

Were you able to find a solution?
